### ISSUE TITLE
Better commands name

### ISSUE THREAD

**Issue by lnc3l0t** [Rawnly/gist.nvim#11]
I think prefixing the plugin "name" is better than suffixing it.

Let's have the commands become:
- `CreateGist` -> `GistCreate`
- `CreateGistFromFile` -> `GistFromFile`
- `ListGists` -> `GistsList`

I think the commands may be more easily remembered

**Comment by Rawnly** [comment]
LGTM I'll do a pr by the end of the day, I think i'll keep old names for this release and remove them in the next one. In order to let people easily migrate. (maybe with a warning)

**Comment by Rawnly** [comment]
Uh! Thank you!
