### ISSUE TITLE
Error when creating gist

### ISSUE THREAD

**Issue by AlexXi19** [rawnly/gist.nvim#16]
Hey love the idea of this plugin, but when i create a gist for standalone python files, these error happens. 

![image](https://github.com/rawnly/gist.nvim/assets/68758451/2f42dce9-cf3e-4216-86a5-b11829fc119e)

![image](https://github.com/rawnly/gist.nvim/assets/68758451/de7a01ff-0ee7-497a-9887-f496b7a9b57f)

After the first error happens, my nvim ui gets messed up too. In both cases, the gists are created correctly. 

Interestingly, this doesn't happen for python files (or other files) that are within a github repo, not sure if this is correlated.

**Comment by rawnly** [comment]
Hey thanks for reporting this! I cannot reproduce the error above, but from the screenshot you provided looks like a [`gh`](https://github.com/cli/cli) issue.

**Comment by rawnly** [comment]
Regarding the UI issue, I'm aware of it, unfortunately i'm not very experienced in VIM extensions and I'm currently unaware of the cause of it.

**Comment by AlexXi19** [comment]
Ok thanks, I forked the repo and will play around when i have some time, thanks for making this!

**Comment by rawnly** [comment]
you could try running the same command in the shell and see what happens
